

function GenBaziChart(){
    var BaziChart = [];

    BaziChart.push('<table class="BaziChartTbl">');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlignNoBorder"><div class="命盤豎標題">資訊</div></td>');
    BaziChart.push('<td colspan="8" class="tdAlignNoBorder"><div class="生日資訊" id="mpxs-生日資訊">陽男</div></td>');
    BaziChart.push('<td colspan="4" rowspan="3" class="tdAlignNoBorder"><div class="商標格子"><img id="ChartHeaderImg" class="displayed" alt="ChartHeaderImg" width="120" height="70" src=' + 系統.系統.HeaderImg+'></div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlignNoBorder"><div class="命盤豎標題">西曆</div></td>');
    BaziChart.push('<td colspan="8" class="tdAlignNoBorder"><div class="生日資訊" id="mpxs-西曆生日">1972</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlignNoBorder"><div class="命盤豎標題">農曆</div></td>');
    BaziChart.push('<td colspan="8" class="tdAlignNoBorder"><div class="生日資訊" id="mpxs-農曆生日">1972（壬子）年5（閏）月5日早子時</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td colspan="13" class="tdAlign"><div class="主題橫幅" id="橫幅名稱">八 子 排 盤</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題">四柱</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="四柱格子">時柱</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="四柱格子">日柱</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="四柱格子">月柱</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="四柱格子">年柱</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="四柱格子">大運</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="四柱格子">流年</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題">主星</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="主星格子 mpxs-本命十神" id="mpxs-時干十神">時十</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="主星格子" id="mpxs-日元">日元</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="主星格子 mpxs-本命十神" id="mpxs-月干十神">月十</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="主星格子 mpxs-本命十神" id="mpxs-年干十神">年十</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="主星格子 mpxs-流運十神" id="mpxs-大運十神">大十</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="主星格子 mpxs-流運十神" id="mpxs-流年十神">流十</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題干支">天干</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-時干">甲</div ></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-日干">乙</div ></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-月干">丙</div ></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-年干">丁</div ></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-流運八字干支" id="mpxs-大運干">戊</div ></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-流運八字干支" id="mpxs-流年干">己</div ></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題干支">地支</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-時支">子</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-日支">丑</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-月支">寅</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-本命八字干支" id="mpxs-年支">卯</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-流運八字干支" id="mpxs-大運支">辰</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="八字格子 mpxs-流運八字干支" id="mpxs-流年支">巳</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題">藏干</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="藏干格子" id="mpxs-時藏干"><span class="mpxs-本命八字干支" id="mpxs-時支藏干1">癸</span><span class="mpxs-本命八字干支" id="mpxs-時支藏干2"></span><span class="mpxs-本命八字干支" id="mpxs-時支藏干3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="藏干格子" id="mpxs-日藏干"><span class="mpxs-本命八字干支" id="mpxs-日支藏干1">己</span><span class="mpxs-本命八字干支" id="mpxs-日支藏干2">癸</span><span class="mpxs-本命八字干支" id="mpxs-日支藏干3">辛</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="藏干格子" id="mpxs-月藏干"><span class="mpxs-本命八字干支" id="mpxs-月支藏干1"></span><span class="mpxs-本命八字干支" id="mpxs-月支藏干2"></span><span class="mpxs-本命八字干支" id="mpxs-月支藏干3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="藏干格子" id="mpxs-年藏干"><span class="mpxs-本命八字干支" id="mpxs-年支藏干1"></span><span class="mpxs-本命八字干支" id="mpxs-年支藏干2"></span><span class="mpxs-本命八字干支" id="mpxs-年支藏干3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="藏干格子" id="mpxs-大運藏干"><span class="mpxs-流運八字干支" id="mpxs-大運藏干1"></span><span class="mpxs-流運八字干支" id="mpxs-大運藏干2"></span><span class="mpxs-流運八字干支" id="mpxs-大運藏干3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="藏干格子" id="mpxs-流年藏干"><span class="mpxs-流運八字干支" id="mpxs-流年藏干1"></span><span class="mpxs-流運八字干支" id="mpxs-流年藏干2"></span><span class="mpxs-流運八字干支" id="mpxs-流年藏干3"></span></div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題副星">副星</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="副星格子"><span class="mpxs-本命十神" id="mpxs-時副星1"></span><BR><span class="mpxs-本命十神" id="mpxs-時副星2"></span><BR><span class="mpxs-本命十神" id="mpxs-時副星3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="副星格子"><span class="mpxs-本命十神" id="mpxs-日副星1">偏財</span><BR><span class="mpxs-本命十神" id="mpxs-日副星2">偏印</span><BR><span class="mpxs-本命十神" id="mpxs-日副星3">七殺</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="副星格子"><span class="mpxs-本命十神" id="mpxs-月副星1"></span><BR><span class="mpxs-本命十神" id="mpxs-月副星2"></span><BR><span class="mpxs-本命十神" id="mpxs-月副星3"></span></div></td> ');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="副星格子"><span class="mpxs-本命十神" id="mpxs-年副星1"></span><BR><span class="mpxs-本命十神" id="mpxs-年副星2"></span><BR><span class="mpxs-本命十神" id="mpxs-年副星3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="副星格子"><span class="mpxs-流運十神" id="mpxs-大運副星1"></span><BR><span class="mpxs-流運十神" id="mpxs-大運副星2"></span><BR><span class="mpxs-流運十神" id="mpxs-大運副星3"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="副星格子"><span class="mpxs-流運十神" id="mpxs-流年副星1"></span><BR><span class="mpxs-流運十神" id="mpxs-流年副星2"></span><BR><span class="mpxs-流運十神" id="mpxs-流年副星3"></span></div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題">運星</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="運星格子"><span id="mpxs-時運星">死</span><BR><span>49-64</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="運星格子"><span id="mpxs-日運星"></span><BR><span>33-48</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="運星格子"><span id="mpxs-月運星"></span><BR><span>17-32</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="運星格子"><span id="mpxs-年運星"></span><BR><span>1-16</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="運星格子"><span id="mpxs-大運運星"></span><BR><span id="mpxs-大運歲數間距"></span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="運星格子"><span id="mpxs-流年運星"></span><BR><span id="mpxs-當選流年年份"></span></div></td>');
    BaziChart.push('</tr>');

    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題">納音</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="納音格子"><span class="mpxs-本命纳音" id="mpxs-時柱納音">---</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="納音格子"><span class="mpxs-本命纳音" id="mpxs-日柱納音">---</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="納音格子"><span class="mpxs-本命纳音" id="mpxs-月柱納音">---</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="納音格子"><span class="mpxs-本命纳音" id="mpxs-年柱納音">---</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="納音格子"><span class="mpxs-流運纳音" id="mpxs-大運納音">---</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="納音格子"><span class="mpxs-流運纳音" id="mpxs-流年納音">---</span></div></td>');
    BaziChart.push('</tr>');

    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="命盤豎標題">神煞</div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="神煞格子"><span id="mpxs-時柱神煞">----<br>學堂<br>金轝<br>劫殺<br>將星</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="神煞格子"><span id="mpxs-日柱神煞">----</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="神煞格子"><span id="mpxs-月柱神煞">----</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="神煞格子"><span id="mpxs-年柱神煞">----</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="神煞格子"><span id="mpxs-大運神煞">----</span></div></td>');
    BaziChart.push('<td colspan="2" class="tdAlign"><div class="神煞格子"><span id="mpxs-流年神煞">----</span></div></td>');
    BaziChart.push('</tr>');

    BaziChart.push('<tr>');
    BaziChart.push('<td rowspan="3" class="tdAlign"><div class="命盤豎標題大運流年">大運</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運0干支" data-大運數="0">小運</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運1干支" data-大運數="1">乙丑</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運2干支" data-大運數="2">乙丑</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運3干支" data-大運數="3">丙寅</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運4干支" data-大運數="4">丁卯</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運5干支" data-大運數="5">戊辰</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運6干支" data-大運數="6">己巳</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運7干支" data-大運數="7">庚午</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="大運干支格子" id="mpxs-大運8干支" data-大運數="8">辛未</div></td>');
    BaziChart.push('<td colspan="3" rowspan="3" class="tdAlign"><div class="資訊格子1" style="margin-left:0px;"><img class="displayed" alt="Logo" height="72px" width="100px" src=' + 系統.系統.BodyImg+'></div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>  ');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運0起歲">1</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運1起歲">8</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運2起歲">18</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運3起歲">28</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運4起歲">38</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運5起歲">48</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運6起歲">58</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運7起歲">68</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運8起歲">7</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運0起年">1972</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運1起年">1979</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運2起年">1989</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運3起年">1999</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運4起年">2009</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運5起年">2019</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運6起年">2029</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運7起年">2039</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-大運8起年">2049</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>  ');
    BaziChart.push('<td rowspan="3" class="tdAlign"><div class="命盤豎標題大運流年">流年</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年0干支" data-流年數="0">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年1干支" data-流年數="1">乙丑</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年2干支" data-流年數="2">丙寅</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年3干支" data-流年數="3">丁卯</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年4干支" data-流年數="4">戊辰</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年5干支" data-流年數="5">己巳</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年6干支" data-流年數="6">庚午</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年7干支" data-流年數="7">辛未</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年8干支" data-流年數="8">壬申</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流年干支格子" id="mpxs-流年9干支" data-流年數="9">癸酉</div></td>');
    BaziChart.push('<td colspan="2" rowspan="3" class="tdAlign"><div class="資訊格子2">程式：<br>&copy五虎遁<br><br>版本：<br><span id="版本名稱">測試版v0.3</span></div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年0歲數">38</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年1歲數">39</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年2歲數">40</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年3歲數">41</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年4歲數">42</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年5歲數">43</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年6歲數">44</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年7歲數">45</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年8歲數">46</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年9歲數">47</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr> <!--<span class="流運年歲格子" id="mpxs-流年0年份"></span>-->');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年0年份">2009</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年1年份">2010</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年2年份">2011</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年3年份">2012</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年4年份">2013</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年5年份">2014</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年6年份">2015</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年7年份">2016</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年8年份">2017</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子" id="mpxs-流年9年份">2018</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td rowspan="2" class="tdAlign"><div class="命盤豎標題流月">流月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月0干支" data-流月數="0">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月1干支" data-流月數="1">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月2干支" data-流月數="2">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月3干支" data-流月數="3">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月4干支" data-流月數="4">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月5干支" data-流月數="5">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月6干支" data-流月數="6">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月7干支" data-流月數="7">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月8干支" data-流月數="8">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月9干支" data-流月數="9">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月10干支" data-流月數="10">甲子</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流月干支格子" id="mpxs-流月11干支" data-流月數="11">甲子</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('<tr>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">1月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">2月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">3月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">4月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">5月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">6月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">7月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">8月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">9月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">10月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">11月</div></td>');
    BaziChart.push('<td class="tdAlign"><div class="流運年歲格子">12月</div></td>');
    BaziChart.push('</tr>');
    BaziChart.push('</table>');
    return BaziChart.join("");
}

function 建立五行開運內容(){
    var 五行開運內容 = [];

    五行開運內容.push('<div class="panel-group" id="acc-五行開運">');
    五行開運內容.push('<div class="panel panel-default">');
    五行開運內容.push('<div class="panel-heading">');
    五行開運內容.push('<h4 class="panel-title">');
    五行開運內容.push('<a data-toggle="collapse" data-parent="#acc-五行開運" href="#col-喜木">五行喜木</a>');
    五行開運內容.push('</h4>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div id="col-喜木" class="panel-collapse collapse">');
    五行開運內容.push('<div class="panel-body">');
    五行開運內容.push('命喜木之人，平時多穿著綠色衣服、佩飾，或家裏之牆壁、沙發、窗簾、衣櫥，家具等儘量採用綠色或靑色系列，有助於開運。尤其是求職之面談，或交易之談判等事件。<br><br>');
    五行開運內容.push('命喜木者，較宜居住於溫帶地區，喜多林木之區域，如公園、植物園、近山林之地方。就寢時頭部朝東較佳。<br><br>');
    五行開運內容.push('開運物品：蜜蠟、石榴石、紅發晶、玫瑰輝石。<br><br>');
    五行開運內容.push('幸運數字：1、2。<br><br>');
    五行開運內容.push('職業：木材等、木製家具、裝潢業、木製藝品業、木匠、簿記員、秘書、速記打字員、出納員、護士、教師、文具店、文化事業(不含直接出版者)、校長、教育界及器具業、服裝師、作家、實驗室助理、書店、種植花卉藝術業、樹苗業、青果商、西藥房、藥劑師、圖書館員、園藝設計業、布匹買賣業、售賣植物性之素食業、蔬菜種作栽培研究業、物理研究員、生物學家、固定性公務人員、販賣青草店、特殊有機體成長研究員、技術性專業傳授、司機、竹製家具業、竹製裝飾品、藤製品、工業技術執行部門、操作員、人士培育輔導員及企劃設計部門等。<br><br>');
    五行開運內容.push('食療：綠豆、韭菜、蒜苗、油菜、小白菜、芥蘭、菠菜、空心菜、西洋菜、萵苣、莧菜、芹菜、豌豆莢、四季豆、蘆筍、綠花椰菜、絲瓜、黃瓜、青椒、香菜、九層塔、青蔥、綠茶、香瓜、棗、葡萄、奇異果、芭樂、哈密瓜、青蘋果、動物肝臟。<br><br>');
    五行開運內容.push('五行屬木的字列表：<br>');
    五行開運內容.push('木　未　本　術　朱　朴　朵　機　權　杉　杏　材　村　杓　杜　杞　楊　杭　杯　杰　杲　杷　杼　鬆　極　構　枇　枋　析　林　枚　果　枝　樅　樞　櫪　枧　棖　楓　枰　枳　枸　柄　柅　柏　柚　柞　檸　柯　柱　柳　柴　檉　柿　柵　標　棧　櫛　櫳　棟　樹　栒　栓　栗　栟　校　栩　株　栫　樣　根　格　桀　桁　桂　桃　桄　桅　桉　桐　桑　桓　桔　椏　楨　榿　橋　樺　檜　桷　梃　梅　梒　梓　梡　梢　梣　夢　梧　梭　梯　械　梵　檢　棉　棋　棌　棒　棕　棚　棠　棣　棨　棫　森　棱　棹　棼　椅　椆　椈　植　椐　椴　椽　椿　楗　楙　楚　楟　楠　楣　楦　楫　楮　楷　楸　楹　樓　概　欖　榆　櫚　櫸　榔　榕　榘　榛　榜　榭　榴　盤　槎　槐　檳　槯　槿　樊　樗　樟　模　樨　橫　檣　櫻　樵　樽　橘　橙　櫓　檀　檄　檞　檠　檬　欣　款　歇　歌　毅　相　科　秴　稀　稕　稷　稻　稼　稽　竹　竺　竽　篤　笄　笆　笒　筆　笗　笙　笛　笠　笥　符　第　笭　笮　笳　箋　等　筌　筏　筐　筑　答　策　筠　筱　筵　籌　簡　箐　箕　管　簫　箭　箴　篁　篇　籃　籬　簇　簟　簪　籟　籍　粉　耕　聯　聿　肖　肯　胤　艦　舸　藝　艽　芃　芄　芊　芋　芍　芏　芑　芒　薌　芙　蕪　芝　芠　芣　芥　蘆　芩　芪　芫　芬　芭　芯　花　芳　芷　芸　芹　芽　芾　蓯　苄　葦　莧　萇　蒼　苧　蘇　苑　苒　苓　苔　苕　苜　苞　苡　苣　若　苧　苪　英　苳　苴　蘋　苻　苼　苾　茁　茂　茅　茉　茗　茚　茜　茞　茥　茨　茪　茬　茭　茯　茱　茴　茵　茶　茸　茹　茽　荀　荃　草　荋　荏　薦　荑　荒　荔　荙　蕘　蓽　蕎　薈　薺　荢　榮　犖　藎　蓀　蔭　葒　荮　荶　荷　荸　荹　荺　荻　莀　蒞　莆　莉　莋　莎　莐　莑　莒　莓　莘　莛　莞　莟　莨　莩　莪　萊　蓮　蒔　獲　瑩　鶯　莼　莽　菀　菁　菂　菅　菇　菉　菊　菖　菘　菡　菪　菱　菲　菽　萁　萂　萃　萄　萌　萗　蘿　螢　營　縈　蕭　薩　萪　萱　萸　萼　葃　葆　葇　葎　葑　葛　葟　葡　葭　葮　葳　葵　葹　蒂　蒄　蒟　蒨　蒲　蒸　蒹　蓁　蓄　蓉　蓓　蓕　藍　蓬　蓼　蔀　蔓　蔚　蔟　蔡　蔬　薔　蕃　蕉　蕊　蕖　蕙　蕤　蘊　蕾　薇　薏　薛　薪　薷　藏　蘚　藜　藠　藤　藿　蘅　虯　虹　蛟　見　觀　規　覺　覯　覲　角　谷　贛　赫　起　趁　躬　輥　軌　軛　軻　輕　輥　過　近　迥　迦　迭　逑　遇　遒　雋　雁　雅　集');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div class="panel panel-default">');
    五行開運內容.push('<div class="panel-heading">');
    五行開運內容.push('<h4 class="panel-title">');
    五行開運內容.push('<a data-toggle="collapse" data-parent="#acc-五行開運" href="#col-喜火">五行喜火</a>');
    五行開運內容.push('</h4>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div id="col-喜火" class="panel-collapse collapse">');
    五行開運內容.push('<div class="panel-body">');
    五行開運內容.push('命喜火之人，平時多穿著紅色衣服、佩飾，或家裡之牆壁、沙發、窗簾、衣櫥、家具等儘量採用紅色系列，有助於開運。<br><br>');
    五行開運內容.push('命喜火者，較宜居住於熱帶地區，大陸性區域較有利，或居住於乾燥、近火之區域。就寢時頭部宜朝南。<br><br>');
    五行開運內容.push('開運物品：鑽石、黃水晶、琥珀、虎眼石。<br><br>');
    五行開運內容.push('幸運數字：3、4。<br><br>');
    五行開運內容.push('職業：電器業、照明設備業、舞台燈光業、鍋爐設備業、馬達動力業、加工製品合成業、高溫處理業、雷射反應處理、ｘ光處理部門、照相業、沖洗相片業、工業產品再製業、化學反應易燃品、硬化劑製售業、理電髮院、化妝品製造業、熱飲食業、油湯食品業、廚師、照相師、工商管理顧問、教官、人事管理事、電機工程師、警察、女管家、公務領導人、軍人、司法部、治安警備、政治參與者、人事培育訓練員、訓導人員、長官、董事長或總經理有實權領導者、執行政業者、鑄造業、評論家、演說家、鐘錶業、焚化燃燒員、機車汽車火車引擎業、核能反應處理業、電力電信業及塑膠成品業。<br><br>');
    五行開運內容.push('食療：紫山藥、紅豆、紅甜椒、胡蘿蔔、紅辣椒、茄子、紅紫蘇、枸杞、紅棗、櫻桃、水蜜桃、蘋果、草莓、紅肉西瓜、火龍果、番茄、紅肉葡萄柚、桑葚、紅砂糖、動物心臟。<br><br>');
    五行開運內容.push('五行屬火的字列表：<br>');
    五行開運內容.push('丁　丙　叢　兩　中　豐　臨　丹　麗　乃　之　樂　了　爭　二　亭　亮　亶　從　侖　仝　代　令　仲　傳　倫　伶　佁　佃　住　體　佟　佰　侗　侶　偵　儂　俊　俐　儷　倓　倜　倬　值　停　傣　儋　兆　光　黨　全　六　典　內　冉　農　冬　涼　玬　劉　利　勺　午　卓　單　南　盧　廳　歷　厲　厥　疊　另　隻　召　台　同　呂　聽　呈　哲　唐　囡　團　圖　夏　多　大　天　太　頭　奈　奏　獎　女　奴　妡　妥　妮　妲　妶　姈　姊　姐　姞　姯　姳　婁　娌　娘　娜　娢　娣　娳　婷　媛　嫙　嫚　嫝　娘　寧　宅　宕　定　寶　寍　對　尋　導　將　爾　塵　年　廬　底　龐　庭　廷　弄　弋　當　錄　彤　彨　彰　徹　征　待　律　徒　循　徭　征　德　志　忠　念　憐　恁　戀　恕　恬　愷　悌　惕　戴　托　執　揚　摶　掄　拉　拓　招　擇　拿　振　挺　掣　攝　擺　搖　撰　支　政　敕　敦　斕　斗　旅　日　旦　旨　旲　旻　昆　昉　昊　易　昕　曇　昜　映　昭　昮　昱　昸　顯　晃　晉　曉　曄　晗　晞　晟　晢　晴　晶　晸　智　暖　曜　曣　曦　曷　朔　朕　朗　李　來　梁　梨　止　段　殿　毓　求　泰　浥　湟　滕　火　燈　靈　灶　灼　燦　煬　炅　炆　爐　炎　炓　炔　炘　煒　炫　炯　炳　煉　熾　爍　烄　烈　烋　烘　烜　煙　燁　熱　烽　焓　煥　燾　焙　焜　焠　焮　焯　焰　焱　煊　煌　煓　煜　照　熀　熔　熠　颎　熹　燔　燠　燦　燧　燮　爵　爻　特　犁　狄　瓴　甜　田　男　甸　町　暢　畋　留　略　畹　登　的　皚　皞　盞　直　盾　睞　督　睦　瞅　瞳　瞻　矍　知　禮　祉　祝　禎　祿　離　種　秦　秧　秩　積　程　稔　窈　立　站　章　端　糧　粼　繇　納　縱　綸　練　繹　絛　績　綾　綽　綠　緹　緞　緩　締　繚　罔　羅　羚　翀　翃　翎　耀　耐　耳　耽　耿　聃　聆　職　肨　冑　膽　能　臘　騰　自　至　致　臻　舵　艇　良　虞　蛋　蝶　衷　裎　裳　褚　襄　覽　詹　謄　讓　訊　訥　論　証　諍　諾　讀　諒　談　諦　譚　豆　貞　質　贄　賴　贏　趙　足　路　跳　踐　踆　躊　蹈　轉　輪　軸　軼　軫　軺　輅　輦　轍　遼　達　迅　進　連　邇　迪　跡　適　逖　通　逞　遂　道　遙　鄧　那　鄰　郅　郎　酈　鄲　都　醍　採　裡　重　量　鈥　長　閏　闥　閬　闡　隊　陣　陀　際　陸　隴　陳　除　陵　陶　隆　隸　雉　靂　零　鞅　韜　颙　頂　頑　頓　領　題　飄　黛　鼎　鼐　齡　龍');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div class="panel panel-default">');
    五行開運內容.push('<div class="panel-heading">');
    五行開運內容.push('<h4 class="panel-title">');
    五行開運內容.push('<a data-toggle="collapse" data-parent="#acc-五行開運" href="#col-喜土">五行喜土</a>');
    五行開運內容.push('</h4>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div id="col-喜土" class="panel-collapse collapse">');
    五行開運內容.push('<div class="panel-body">');
    五行開運內容.push('命喜土之人，平時多穿著黃色衣服、佩飾，或家裡之牆壁、沙發、窗簾、衣櫥、家具等儘量採用黃色系列，有助於開運。<br><br>');
    五行開運內容.push('命喜土者，較宜居住於不溫不寒且靠近山嶺或接近田園耕作之地區爲佳。就寢時頭部宜朝南。<br><br>');
    五行開運內容.push('開運物品：玉、白幽靈、鈦晶。<br><br>');
    五行開運內容.push('幸運數字：5、6。<br><br>');
    五行開運內容.push('職業：建築業、石材業、石材製品業、礦石業、房地產買賣業、掮客、中盤批發商、介紹業、存貨清查員、倉儲業、泥木匠、拗磚工、磁磚製售業、磁器業、傳教士、牧師、建築管理師、統計師、和尚、尼姑、修道者、殯儀館、打石店、墓碑店、喪儀社、墓地管理經營業、收斂者、石油之原油在未提煉前、代書、山產業、農夫、礦冶工程師、地下工程業、挖鑽施工業、水泥製品業、混凝土業、食用農產品業、印章製造業、當鋪業、土木業、圖書館業、製糊或售糊業、保母業、防水處理業、雨衣雨具業、鞋業、綜合徵信業、資訊業、飼料製售業、五術研究機構、保險業、會統系部門、考古跡古董業、宗教寺廟宮壇管理經營業等。<br><br>');
    五行開運內容.push('食療：薏仁、胚芽米、栗子、地瓜、糙米、蓮藕、玉米、芋頭、小米、燕麥、芋頭、南瓜、黃甜椒、黃豆芽、金針花、玉米筍、黃豆、豆干、素雞、麵腸、麵錢、油豆腐、味噌、蛋黃、豆腐乳、麵筋球、素肉、烤麩、豆腐衣、老薑、橘子、柳丁、楊桃、黃奇異果、檸檬、鳳梨、枇杷、柿子、黃肉西瓜、柑橘、榴槤、芒果、木瓜、金桔、白果、甘蔗汁、水蜜桃、花生、核桃、瓜子、腰果、奶油、乳酪、食用油、咖哩、蜂蜜、動物胃腸。<br><br>');
    五行開運內容.push('五行屬土的字列表：<br>');
    五行開運內容.push('一　與　丫　丸　為　乙　也　予　於　亞　亦　億　仔　以　伊　伍　優　偉　似　位　佑　余　佚　侑　依　侞　俑　傐　傲　兀　允　充　養　冶　准　凹　切　勇　勛　勖　醫　衛　原　又　友　右　葉　員　嗚　詠　唯　喁　喦　因　園　圍　囿　圓　土　聖　圩　圭　圯　地　圳　圻　坂　均　坊　坎　塊　壇　壢　坡　坤　坦　坪　坭　垅　型　壘　垓　垚　垠　垣　墾　塏　埃　城　埏　埔　埕　塤　埜　域　埮　培　基　埼　堂　堃　堆　堉　堡　堤　堦　堭　堰　塅　塘　塾　墀　境　墉　墐　牆　墝　增　墩　壁　壅　壑　壕　壤　壹　夜　央　夷　奎　奧　嬰　宇　安　完　宛　宥　宴　容　寅　尉　尤　尹　山　屴　屹　嶼　岍　岐　崗　峴　嵐　岦　岩　岫　嶺　岷　岽　巋　嶧　峋　峘　峽　嶠　崢　峧　峨　峭　崌　崎　崑　崖　崚　崛　崟　崡　崧　崨　崮　崴　嵂　嵃　嵈　嵋　嵎　嵑　嶸　嵙　嵚　嵢　嵩　嵫　嵹　嶂　嶒　嶙　嶝　巔　巍　己　幃　帷　幼　幽　應　庸　延　異　引　彝　彧　影　徫　憶　怡　懌　恩　惲　悠　惟　慣　意　慰　懿　戊　戌　戍　抑　擁　揖　援　攸　敖　旖　旺　昀　昶　晏　有　歐　欲　殷　氤　溫　焉　燕　爰　愛　牡　牽　猶　猷　王　玥　瑋　琬　瑕　瑛　璦　瓔　璧　瓦　用　甬　由　畫　畏　畯　疄　疆　益　盎　眙　眺　矣　磯　礬　礦　硯　砜　砥　礪　礱　礫　礎　硌　碩　確　碁　碚　碟　磁　磊　磐　磨　礡　禹　稚　穩　窕　約　緯　維　緣　纓　羊　羭　羽　羾　翁　翂　翌　翔　翕　翙　翞　翟　耶　育　胃　胡　膺　艮　艷　艾　融　衡　衣　袁　袂　裊　袔　袺　裔　褆　褕　褘　褸　要　譽　詒　話　誕　詣　詡　謂　諳　豌　豫　貽　越　躍　踴　蹦　軒　輊　轅　辰　迎　運　遠　逵　逸　遐　遨　邑　邨　鄴　鄆　鄖　鄞　野　閨　閱　阪　陽　阿　附　院　隱　雍　鞍　韋　韞　音　韻　頊　頤　飲　飴　餘　驁　鰲　鷨　鳥　鳶　鷗　鴛　鸻　鸚　黃');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div class="panel panel-default">');
    五行開運內容.push('<div class="panel-heading">');
    五行開運內容.push('<h4 class="panel-title">');
    五行開運內容.push('<a data-toggle="collapse" data-parent="#acc-五行開運" href="#col-喜金">五行喜金</a>');
    五行開運內容.push('</h4>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div id="col-喜金" class="panel-collapse collapse">');
    五行開運內容.push('<div class="panel-body">');
    五行開運內容.push('命喜金之人，平時多穿著白色衣服、佩飾，或家裡之牆壁、沙發、窗簾、衣櫥、家具等儘量採用白色系列，有助於開運。<br><br>');
    五行開運內容.push('命喜金者，較宜居住於涼性地區，及接近金屬或礦區爲佳。就寢時頭部宜朝西。<br><br>');
    五行開運內容.push('開運物品：黃白金、白幽靈、翡翠、東菱石。<br><br>');
    五行開運內容.push('幸運數字：7、8。<br><br>');
    五行開運內容.push('職業：金屬工具材料業、機械製造業、鐵工廠、西工黑手界、金玉珠寶製售業、武器製造業、打鐵店、五金製品業、鋁窗工程業、採購員、雕刻業、鐵模工、外科醫生、牙醫、律師、法官、審判員、執行者、音樂家、裁縫師、金融界、爆破業、特殊冒險任務執行者、思想滲透部門、調查門部門、堅硬技術業、超鋼鑽石處理切割業、鑽具製售業、交通器具販售業、鑑定師、科技專業門(屬獨立超然系統)、能自我決斷發揮的事業，為主宰關鍵之部門而非領導者、記者、新聞傳播業、民意代表、消費者基金會、公務稽核人員、稅捐部門、公懲會、屠宰業、獸肉販賣業、拆船、拆屋、破壞業、度量衡、鏡業等。<br><br>');
    五行開運內容.push('食療：白米、糯米、山藥、蓮子、荸薺、百合、馬鈴薯、麵粉、涼粉、高麗菜、白蘿蔔、洋蔥、大蒜、包心菜、小白菜、苦瓜、冬瓜、花椰菜、竹筍、白木耳、白蒟蒻、綠豆芽、薑、磨菇、金針菇、鮑魚菇、豆漿、豆腐、雞蛋、鴨蛋、荔枝、龍眼、紅毛丹、柚子、椰子、水梨、香蕉、山竹、杏仁、白芝麻、冰糖、動物肺臟。<br><br>');
    五行開運內容.push('五行屬金的字列表：<br>');
    五行開運內容.push('七　三　上　專　世　絲　丞　主　乘　書　事　產　人　什　仁　仇　仍　倉　仕　仙　仞　仟　任　眾　伸　佐　作　佺　侃　儕　促　俗　俞　信　修　倝　倡　倩　倪　償　儲　僖　僧　僳　儒　兒　先　兌　兟　入　兮　茲　冊　再　沖　淨　憑　出　刀　芻　劃　則　剛　創　初　剴　劍　助　劭　勢　勘　十　千　升　參　雙　叔　取　受　敘　史　司　唱　商　善　宋　宗　宙　實　寵　審　宣　宮　宰　宵　宸　寂　寔　察　寸　壽　尊　小　少　尚　屢　歲　峙　峻　崇　崈　川　州　巡　帥　師　幟　幀　席　幬　常　庄　序　庚　庥　度　庶　徐　得　徽　心　忱　忴　思　性　總　悉　悅　情　想　惺　愁　愈　愉　愔　慈　慎　憇　憧　戈　成　戰　才　扎　承　抒　拙　拯　持　摯　捷　授　推　措　揌　操　攢　敞　數　整　敷　齋　斯　新　施　旋　旌　族　早　旬　時　昌　星　春　昨　是　昰　晝　晁　晨　晰　暄　暠　暹　曳　曹　曾　替　朝　束　棗　柔　查　栽　次　歆　正　此　殊　氏　氫　爽　犀　獅　率　玕　玗　玟　玠　環　玾　珅　珆　珊　琺　珒　珓　珖　珘　珛　珠　珨　珪　珵　珹　琗　琛　琤　琩　琮　琸　琺　玚　瑖　瑜　瑞　瑢　瑧　瑨　璀　璟　璥　璨　瓚　瓷　甚　生　甡　甥　寧　申　疇　皒　盛　真　睜　睢　睬　睿　瞬　矗　社　祖　神　祥　禪　穿　窗　竣　童　竦　纖　純　紓　線　組　紳　細　織　紹　絨　絢　繡　緒　續　綬　綢　綜　縝　繕　罡　羲　而　聳　聚　聰　肅　勝　胥　臣　臧　舂　輿　舍　舒　舜　舟　艙　舷　船　節　著　蠶　蚩　蜀　蟬　蟾　銜　襯　衽　袖　裕　襦　西　謦　認　設　識　詞　詔　譯　詩　誠　詢　詳　詫　說　誦　諸　諗　諄　諶　謁　諭　諼　謚　貂　財　貯　貳　資　賞　賜　賽　賾　贊　赤　走　超　躇　身　車　軔　軾　載　輯　辛　辭　遷　遲　述　選　遜　逍　途　速　造　逾　遵　邃　邵　郝　酉　酌　酥　酬　醒　釋　金　鑒　铚　鑾　鋆　鑫　針　釗　釧　釤　釩　釣　釵　鈦　鐘　鋇　鋼　鈐　鑰　欽　鈞　鈁　鈕　鈺　錢　鉦　鈸　鑽　鈿　鐵　鉑　鈴　鑠　鉛　鉉　鈮　鐸　銅　鎧　銓　銚　銘　錚　鉸　銥　銨　銀　鑄　鋪　錸　鏈　鏗　鎖　鋤　鋯　鋨　鋒　鋅　銳　錨　錫　錘　錦　錟　錠　鍵　錳　鍥　鏘　鍶　鍬　鍛　鍰　鍍　鎂　鏤　鎮　鐫　鎬　鎰　鎵　鑌　镕　鏢　鏜　鏡　鐳　鐮　閃　問　閭　雀　雛　雕　雼　青　靚　靖　靜　靛　韶　順');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div class="panel panel-default">');
    五行開運內容.push('<div class="panel-heading">');
    五行開運內容.push('<h4 class="panel-title">');
    五行開運內容.push('<a data-toggle="collapse" data-parent="#acc-五行開運" href="#col-喜水">五行喜水</a>');
    五行開運內容.push('</h4>');
    五行開運內容.push('</div>');
    五行開運內容.push('<div id="col-喜水" class="panel-collapse collapse">');
    五行開運內容.push('<div class="panel-body">');
    五行開運內容.push('命喜水之人，平時多穿著黑色衣服、佩飾，或家裡之牆壁、沙發、窗簾、衣櫥、家具等儘量採用黑色系列，有助於開運。<br><br>');
    五行開運內容.push('命喜水者，較宜居住於寒帶地區或靠近海邊、河川、湖泊等近水之地區爲佳。就寢是頭部宜朝北。<br><br>');
    五行開運內容.push('開運物品：水晶、珍珠、黑曜石、黑碧璽、煙晶。<br><br>');
    五行開運內容.push('幸運數字：9、10。<br><br>');
    五行開運內容.push('職業：推銷員、導遊業、旅行社、牛仔褲販賣業、運動家、娛樂業、色情業、旅社賓館、公共浴室業、溫泉業、流動攤販、水管業、給排水處理業、水肥處理業、郵差、廣告業、出版者、油漆匠、超級商店、社會工作者、舞蹈演藝人員、投機事業、美容師、空中小姐、武術教練、大眾傳播業、漁業界、車掌、清潔清洗業、航海船業公司、船員、打撈業、消防隊、游泳業、衛浴業、股票市場、冷凍事業、冷水冰棒飲料業、蒸餾水業、抽水業、釣魚池業、滅火消防業、貿易業、期貨跑單幫、舶來品報關行、不定性事業、球類運動業、健身房、操體力勞工業、茶室、海產業、水產養殖場及事業、染衣洗衣店、運送店、交通運輸業、航空事業、水利事業、菜市場、藝術業、流動性事業。<br><br>');
    五行開運內容.push('食療：黑木耳、髮菜、草菇、香菇、海菜、海帶、牛蒡、黑蒟蒻、海苔、黑棗、紫山藥、茄子、皮蛋、黑豆漿、黑豆、豆豉、蕎麥麵、龍眼乾、烏梅、葡萄乾、葡萄、藍莓、湖麻油、黑芝麻、醬油、黑醋、茶葉、甜麵醬、豆瓣醬、動物腎臟。<br><br>');
    五行開運內容.push('五行屬水的字列表：<br>');
    五行開運內容.push('萬　丕　習　鄉　買　雲　互　亥　亨　畝　享　仆　付　份　仿　伏　伐　休　會　伯　伴　佛　佩　侯　保　俯　俸　倍　候　傅　興　馮　冰　況　冷　凊　凜　凝　水　永　汀　匯　漢　汋　汌　汍　汐　汕　汛　汝　江　池　湯　汩　汪　汴　汵　汶　汾　沁　沂　沃　沅　沆　沈　沉　沐　沔　沙　沛　灃　淪　滄　沨　溈　滬　沫　沱　河　治　沼　沾　沿　泂　泇　泉　泊　泓　法　泗　泙　泛　濘　泠　泡　波　泥　注　泫　泮　泯　泱　泳　瀧　澤　涇　潔　洇　洊　洋　洌　洒　洗　洚　洛　洞　津　洧　洪　洮　洱　洲　洳　洵　洸　洹　洺　活　洽　派　流　浹　淺　澮　濟　瀏　渾　滸　濃　浙　浚　浛　浣　浦　浩　浪　浮　浴　海　浺　涂　涆　涌　涓　涔　濤　漣　渙　滌　涥　潤　澗　涪　涯　涴　涵　澱　淄　淅　淇　淋　淐　淑　淘　淙　淞　淡　淬　淮　深　淳　添　淼　清　淵　淥　漸　漁　渝　渠　渡　渤　渥　渭　港　渱　渲　游　渺　湃　湄　湉　湑　湖　湘　湛　湜　湝　湳　灣　漵　溎　源　溟　溢　溥　溪　溯　溱　溶　滂　滇　滉　滋　滐　滔　灩　滿　瀅　濱　漂　演　漠　漩　漪　漫　漱　漾　瀠　瀟　濰　潘　潛　潞　潢　潭　潮　潺　潼　潾　澄　澈　澉　澍　澎　澔　澕　瀾　澧　澳　濂　蒙　濠　濡　濮　濯　瀚　瀛　瀞　灝　炬　點　煮　熊　熏　熙　父　牟　牧　物　狀　猛　玄　瓶　甫　畀　畔　痕　白　百　皇　皮　盈　盤　盟　目　盷　盼　眉　眠　眸　睎　瞄　矛　矞　碧　祊　祜　稟　福　禧　箔　米　粱　繁　紅　紛　紋　紡　紱　絎　繪　綏　綿　緬　縛　繽　縹　縵　罕　美　翡　翩　翮　翰　翻　耘　聘　肪　脈　航　舫　般　舶　艗　艴　苗　范　茳　荊　蕩　滎　莫　菏　菠　萍　蒙　藩　藻　虎　虛　虢　蜂　蜜　行　衍　補　表　袓　袤　裘　裱　褒　褓　覓　計　訓　訪　評　謀　謨　謐　譜　豪　豹　貌　貝　貿　賀　賈　賦　赟　跋　蹼　轟　輔　輩　輝　辨　邊　邁　還　迷　逋　逢　遑　邈　邗　邟　邠　邦　邯　邴　邶　郁　合　郇　郛　部　配　酣　酩　醇　釜　钚　門　閑　閔　聞　閩　閣　闊　阜　防　陂　陌　陪　隃　隈　雄　雨　雩　雪　雯　雱　雷　霧　霽　霄　霆　震　霈　霍　霏　沾　霓　霖　霙　霜　霞　露　非　韓　俯　項　頒　頗　頻　頷　風　颮　颯　飆　飚　飛　香　馡　馥　馬　駁　駙　駢　驃　魂　魚　魴　鮑　鳩　鳴　鴻　鵬　鶴　麥　麻');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');
    五行開運內容.push('</div>');

    return 五行開運內容.join("");
}